amazonURI: s3:///s3.amazonaws.com

#SFTP Connection config
sftpConfig:
  port: 21000
  publicKeyFile: src/main/resources/hostKey
authorizedKeysFile:
  src/main/resources/authorized_keys

#SFTP Users and their S3 home buckets
users:
  rossdrew:
    home: hubio-ubi-ftp
  justin:
    home: hubio-ubi-ftp

server:
  port: 8080
