amazonURI: s3:///s3.amazonaws.com

#SFTP Connection config
sftpConfig:
  port: 21000
  publicKeyFile: key2.pem.pub

#SFTP Users and their S3 home buckets
users:
  rossdrew:
    home: hubio-ubi-ftp
  justin:
    home: hubio-ubi-ftp

server:
  port: 8080
